/*
 * DIA – static search (/buscar/?s=term).
 * Loads /assets/search-index.json (generated by the build from data/news and data/personnel)
 * and renders the matches with the same card markup as the archive pages.
 */
(function () {
  'use strict';
  // Base path the site is published under ("/" or e.g. "/repo/" on GitHub Pages), taken from this script's own URL.
  var BASE = ((document.currentScript && document.currentScript.getAttribute('src')) || '').replace(/assets\/js\/.*$/, '') || '/';
  var main = document.querySelector('[data-search-results]');
  if (!main) return;
  var params = new URLSearchParams(location.search);
  var q = (params.get('s') || '').trim();
  document.querySelectorAll('input[name="s"]').forEach(function (i) { i.value = q; });
  if (!q) return;
  var title = document.getElementById('dia-search-title');
  if (title) title.textContent = 'Resultados de búsqueda: «' + q + '»';
  document.title = 'Has buscado ' + q + ' - Departamento de Inteligencia Artificial';

  var norm = function (s) { return (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, ''); };
  var terms = norm(q).split(/\s+/).filter(Boolean);
  var esc = function (s) { return String(s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); };

  fetch(BASE + 'assets/search-index.json').then(function (r) { return r.json(); }).then(function (items) {
    var hits = items.filter(function (it) {
      var hay = norm(it.title + ' ' + it.text);
      return terms.every(function (t) { return hay.indexOf(t) !== -1; });
    });
    if (!hits.length) {
      main.querySelector('.page-content').insertAdjacentHTML('afterbegin', '<p>' + esc(main.getAttribute('data-empty-text')) + '</p>');
      return;
    }
    var html = '<div class="ast-row">' + hits.map(function (it) {
      return '<article class="post ast-col-sm-12 ast-article-post ast-col-md-4 ast-archive-post ast-separate-posts"><div class="ast-post-format- blog-layout-4 ast-article-inner ast-no-date-box"><div class="post-content ast-col-md-12">' +
        (it.image ? '<div class="ast-blog-featured-section post-thumb ast-blog-single-element"><div class="post-thumb-img-content post-thumb"><a href="' + esc(it.url) + '" tabindex="-1" aria-hidden="true"><img src="' + esc(it.image) + '" alt="" loading="lazy"></a></div></div>' : '') +
        '<h2 class="entry-title ast-blog-single-element"><a href="' + esc(it.url) + '" rel="bookmark">' + esc(it.title) + '</a></h2>' +
        (it.date ? '<header class="entry-header ast-blog-single-element ast-blog-meta-container"><div class="entry-meta"><span class="posted-on"><span class="published"> ' + esc(it.date) + ' </span></span></div></header>' : '') +
        '<p class="ast-blog-single-element ast-read-more-container read-more"> <a href="' + esc(it.url) + '"> <span class="screen-reader-text">' + esc(it.title) + '</span> Leer más »</a></p></div></div></article>';
    }).join('') + '</div>';
    main.innerHTML = html;
  }).catch(function () {
    main.querySelector('.page-content').insertAdjacentHTML('afterbegin', '<p>No se ha podido cargar el índice de búsqueda.</p>');
  });
})();
