// Generates docs/url-migration.md: every URL found on the original site (sitemaps + crawl)
// and what serves it in the static build.   Usage: node scripts/validation/url-report.mjs
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const DIST = path.join(ROOT, 'dist');
const report = JSON.parse(fs.readFileSync(path.join(ROOT, '.cache/crawl/crawl-report.json'), 'utf8'));
const redirects = JSON.parse(fs.readFileSync(path.join(ROOT, 'data/redirects.json'), 'utf8')).redirects;
const known = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/validation/known-broken.json'), 'utf8')).links;

const rows = [];
const counts = {};
for (const [url, p] of Object.entries(report.pages).sort(([a], [b]) => a.localeCompare(b))) {
  const u = new URL(url);
  const local = u.pathname.endsWith('/') ? u.pathname : u.pathname + '/';
  const file = path.join(DIST, decodeURIComponent(local), 'index.html');
  const redirect = redirects.find((r) => r.from === local);
  let status; let note = '';
  if (u.search) { status = 'query variant'; note = `WordPress ignored the query (\`${u.search}\`); the static server serves ${u.pathname} for it.`; }
  else if (p.status === 404) { status = 'was 404'; note = (known.find((k) => k.url.replace(/\/$/, '') === u.pathname.replace(/\/$/, '')) || {}).reason || 'Already 404 on the original site (legacy link in content); still 404.'; }
  else if (redirect) { status = 'redirect'; note = `→ ${redirect.to} (static redirect page; configure a 301 on the server)`; }
  else if (fs.existsSync(file)) { status = 'migrated'; }
  else { status = 'MISSING'; }
  counts[status] = (counts[status] || 0) + 1;
  rows.push(`| ${u.pathname}${u.search} | ${status === 'migrated' ? `\`${path.relative(DIST, file).replaceAll('\\', '/')}\`` : '—'} | ${status} | ${note} |`);
}
// pages generated that were not crawled (e.g. pagination beyond what the crawler followed, search)
const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]));
const crawled = new Set(Object.keys(report.pages).map((u) => { const p = new URL(u).pathname; return p.endsWith('/') ? p : p + '/'; }));
const extra = walk(DIST).filter((f) => f.endsWith('index.html')).map((f) => '/' + path.relative(DIST, f).replaceAll('\\', '/').replace(/index\.html$/, '')).filter((p) => !crawled.has(p) && !redirects.some((r) => r.from === p)).sort();

const md = `# URL migration

Generated by \`node scripts/validation/url-report.mjs\` from the crawl of https://dia.fi.upm.es/ (2026-09-26) and the current \`dist/\`.

**Summary:** ${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(' · ')} — ${extra.length} additional page(s) generated.

All public URLs keep their original path: the build writes \`dist/<path>/index.html\`, so \`/contacto/\`, \`/investigacion_dia/\`,
\`/personaldia/asun/\`… work unchanged on nginx/Apache (directory index). URLs without the trailing slash are redirected
to the slash version by the web server (default nginx/Apache behaviour for directories; \`scripts/build/serve.mjs\` does the same).

## Redirects to configure on the server

| Old URL | New URL | Why |
|---|---|---|
${redirects.map((r) => `| ${r.from} | ${r.to} | ${r.reason} |`).join('\n')}
| /wp-content/uploads/* | /assets/uploads/* | Media files were moved out of the WordPress folder structure (same sub-path). Keeps old links to images and PDFs working. |
| /feed/, /comments/feed/, /en/feed/ | /noticias/ | RSS feeds were generated by WordPress (not reproduced; see docs/site-audit.md). |
| /wp-admin/*, /wp-login.php, /xmlrpc.php, /wp-json/* | 410 Gone | WordPress back-office / API, intentionally removed. |

nginx example:

\`\`\`nginx
location ^~ /wp-content/uploads/ { rewrite ^/wp-content/uploads/(.*)$ /assets/uploads/$1 permanent; }
location = /es/marianorico { return 301 /personaldia/marianorico/; }
location ~ ^/(feed|comments/feed|en/feed)/?$ { return 301 /noticias/; }
location ~ ^/(wp-admin|wp-json|wp-includes)/|^/(wp-login|xmlrpc)\\.php { return 410; }
error_page 404 /404.html;
\`\`\`

Apache (\`.htaccess\`) example:

\`\`\`apache
ErrorDocument 404 /404.html
RedirectMatch 301 ^/wp-content/uploads/(.*)$ /assets/uploads/$1
Redirect 301 /es/marianorico /personaldia/marianorico/
RedirectMatch 301 ^/(feed|comments/feed|en/feed)/?$ /noticias/
RedirectMatch 410 ^/(wp-admin|wp-json|wp-includes)/
RedirectMatch 410 ^/(wp-login|xmlrpc)\\.php
\`\`\`

## Every crawled URL

| Original URL | New local file | Status | Notes |
|---|---|---|---|
${rows.join('\n')}

## Additional pages generated by the static build

These URLs exist on the original site too (pagination pages the crawler did not reach, all generated from the same data), or are new:

${extra.map((p) => `- ${p}${p === '/buscar/' ? ' — **new**: static search page that replaces WordPress search (\`/?s=\`)' : ''}`).join('\n')}
`;
fs.writeFileSync(path.join(ROOT, 'docs/url-migration.md'), md);
console.log(counts, 'extra', extra.length);
